config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'employees#index'

  resources :employees do
    collection do
      get :export_file
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  validates :name, :email, :register_number, :cpf, presence: true

  belongs_to :role

  def self.ransackable_attributes(_auth_object = nil)
    %w[name email register_number cpf] + _ransackers.keys
  end

  def self.ransackable_associations(_auth_object = nil)
    super + %w[role]
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :name, presence: true

  has_many :employees, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[name] + _ransackers.keys
  end

  def self.ransackable_associations(_auth_object = nil)
    super + %w[employees]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  def index
    @q = Employee.ransack(params[:q])

    @employees = @q.result(distinct: true).includes(:role).page params[:page]
  end

  def new
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find_by(id: params[:id])
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path, notice: 'Funcionário cadastrado com sucesso!'
    else
      render :new
    end
  end

  def update
    @employee = Employee.find_by(id: params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Funcionário atualizado com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find_by(id: params[:id])

    @employee.destroy

    redirect_to employees_path, notice: 'Funcionário excluído com sucesso!'
  end

  def export_file
    file = ExportFileService.call(Employee.includes(:role).all)

    if file.present?
      download_file(file)
    else
      redirect_to employees_path, notice: 'Não foi possível gerar o arquivo'
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :register_number, :cpf, :role_id)
  end

  def download_file(file)
    send_file(
      file,
      filename: 'employees.xlsx',
      type: 'application/xlsx',
      disposition: 'attachment'
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
    <% if employee.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

        <ul>
            <% employee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="form-floating mb-3">
        <%= form.text_field :name, class: 'form-control', id: 'floatingInput', placeholder: 'Nome' %>
        <%= form.label :name, 'Nome' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.email_field :email, class: 'form-control', id: 'floatingInput', placeholder: 'E-mail' %>
        <%= form.label :email, 'E-mail' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.text_field :register_number, class: 'form-control', id: 'floatingInput', placeholder: 'RG' %>
        <%= form.label :register_number, 'RG' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.text_field :cpf, class: 'form-control', id: 'floatingInput', placeholder: 'CPF' %>
        <%= form.label :cpf, 'CPF' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.collection_select :role_id, Role.all, :id, :name, { prompt: 'Selecione um cargo' }, class: 'form-control', id: 'floatingInput' %>
        <%= form.label :role_id, 'Cargo' %>
    </div>

    <div class="actions text-end">
        <%= form.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<div class='card' style='width: 30rem;'>
    <div class='card-header text-center'>
        <h5>Editar Funcionário</h5>
    </div>
    <div class='card-body'>
        <%= render 'form', employee: @employee %>
    </div>
</div>

app/views/employees/index.html.erb
<div class='container index p-5 list mt-5 mb-5'>
    <div class='row'>
        <div class='col-md-6 mt-5'>
            <h1>Funcionários</h1>
        </div>
        <div class='col-md-6 mt-5 text-end'>
            <%= link_to 'Novo Funcionário', new_employee_path, class: 'btn btn-primary float-right' %>
            <%= link_to 'Gerar Excel', export_file_employees_path, class: 'btn btn-success float-right me-2' %>
        </div>
    </div>

    <div class='row mt-3 mb-3'>
        <div class='col-md-12'>
            <h4 class="color">Pesquisar</h4>
            <%= form_for @q, url: employees_path, method: :get, html: { class: '' } do |f| %>
                <div class='row form-floating m-1 mb-3'>
                    <%= f.text_field :name_or_email_or_role_name_or_register_number_cont, class: 'form-control', placeholder: 'Nome', id: 'floatingInput' %>
                    <%= f.label :name_or_email_or_role_name_or_register_number_cont, 'Pesquise por Nome, Email, CPF, RG ou Cargo' %>
                </div>
                <div class='text-end'>
                    <%= f.submit 'Pesquisar', class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>

    <div class='row'>
        <div class='col-md-12'>
        <table class='table table-striped'>
            <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>RG</th>
                <th>CPF</th>
                <th>Cargo</th>
                <th colspan='3'>Opções</th>
            </tr>
            </thead>
            <tbody>
            <% @employees.each do |employee| %>
                <tr>
                <td><%= employee.name %></td>
                <td><%= employee.email %></td>
                <td><%= employee.register_number %></td>
                <td><%= employee.cpf %></td>
                <td><%= employee.role.name %></td>
                <td>
                    <%= link_to edit_employee_path(employee), class: 'btn btn-primary' do %>
                        <i class="bi bi-pencil-square"></i>
                    <% end %>
                </td>

                <td class='text-center'>
                    <%= button_to employee_path(employee), method: :delete, class: 'btn btn-danger' do %>
                        <i class="bi bi-trash"></i>
                    <% end %>
                </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        </div>
    </div>

    <div class='row mt-5'>
        <div class='col-md-12 d-flex justify-content-center'>
            <%= paginate @employees %>
        </div>
    </div>
</div>

app/views/employees/new.html.erb
<div class='card' style='width: 30rem;'>
    <div class='card-header text-center'>
        <h5>Novo Funcionário</h5>
    </div>
    <div class='card-body'>
        <%= render 'form', employee: @employee %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvcWithBootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to 'MvcWithBootstrap', root_path, class: 'navbar-brand' %>

        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container d-flex justify-content-center align-items-center w-100" style="min-height: 100vh;">
      <%= yield %>
    </div>
  </body>
</html>